version: '3.2'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: image_service
    volumes:
      - .:/image_service
    ports:
      - "8000:8000"