version: '3'

services:

  app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py loaddata initial_role_data.json &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
      - app
    labels:
      io.rancher.container.pull_image: 'always'

volumes:
  pgdata: